using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WPF_Leap_Motion_simulator.Models
{
    enum LabelTypes
    {
        NO_LABEL,
        RECEIVE_SMS_CODE,
        RECEIVE_PHONE_NUMBER,
        RECEIVE_ERROR_SMS_CODE,
        RECEIVE_ERROR_PHONE_NUMBER,
        SUCCESS_RECEIVE_PARCEL_CODE,
        SUCCESS_RECEIVE_MESSAGE,
        SEND_SENDER_TITLE,
        SEND_SENDER_FIRST_NAME,
        SEND_SENDER_ERROR_FIRST_NAME,
        SEND_SENDER_LAST_NAME,
        SEND_SENDER_ERROR_LAST_NAME,
        SEND_SENDER_EMAIL,
        SEND_SENDER_ERROR_EMAIL,
        SEND_SENDER_PHONE_NUMBER,
        SEND_SENDER_ERROR_PHONE_NUMBER,
        SEND_RECEIVER_TITLE,
        SEND_RECEIVER_FIRST_NAME,
        SEND_RECEIVER_ERROR_FIRST_NAME,
        SEND_RECEIVER_LAST_NAME,
        SEND_RECEIVER_ERROR_LAST_NAME,
        SEND_RECEIVER_PHONE_NUMBER,
        SEND_RECEIVER_ERROR_PHONE_NUMBER,
        SEND_RECEIVER_CITY,
        SEND_RECEIVER_ERROR_CITY,
        SEND_RECEIVER_POST_CODE,
        SEND_RECEIVER_ERROR_POST_CODE,
        SEND_RECEIVER_STREET,
        SEND_RECEIVER_ERROR_STREET,
        SEND_RECEIVER_HOUSE_NUMBER,
        SEND_RECEIVER_ERROR_HOUSE_NUMBER,
        SEND_RECEIVER_APARTMENT_NUMBER,
        SEND_RECEIVER_HOUSE_LETTER,
        SEND_RECEIVER_ERROR_HOUSE_LETTER,
        SEND_SUMMARY_SENDER_TITLE,
        SEND_SUMMARY_SENDER_FIRST_NAME,
        SEND_SUMMARY_SENDER_LAST_NAME,
        SEND_SUMMARY_SENDER_EMAIL,
        SEND_SUMMARY_SENDER_PHONE_NUMBER,
        SEND_SUMMARY_RECEIVER_TITLE,
        SEND_SUMMARY_RECEIVER_FIRST_NAME,
        SEND_SUMMARY_RECEIVER_LAST_NAME,
        SEND_SUMMARY_RECEIVER_PHONE_NUMBER,
        SEND_SUMMARY_RECEIVER_CITY,
        SEND_SUMMARY_RECEIVER_POST_CODE,
        SEND_SUMMARY_RECEIVER_STREET,
        SEND_SUMMARY_RECEIVER_HOUSE_NUMBER,
        SEND_SUMMARY_RECEIVER_APARTMENT_NUMBER,
        SEND_SUMMARY_RECEIVER_HOUSE_LETTER,
        SUCCESS_SEND_MESSAGE
    }
}
